# Site settings
title: Résidence Ella
description: > # this means to ignore newlines until "baseurl:"
# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "74mademoiselle.fr" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
