---
services:
- title: Acceuil
  icon: fa-smile-beam
  description: 7/7, 24/24, à votre service...
  delay: 0.2s
- title: Spa
  icon: fa-spa
  description: Sauna et Hammam privatisé
  delay: 0.4s
- title: Ménage
  icon: fa-quidditch
  description: '1 fois tous les 15 jours compris dans les charges du loyer '
  delay: 0.6s
- title: Petit-déjeuner
  icon: fa-mug-hot
  description: En Salle ou en Chambre à vous de choisir (voir tarif)
  delay: 0.8s
- title: Repassage
  icon: fa-tshirt
  description: Repassage sur demande (voir tarif)
  delay: 0.2s
- title: Salle de sport
  icon: fa-dumbbell
  description: Se maintenir en forme, c'est essentiel...
  delay: 0.4s
- title: 'Laverie '
  icon: fa-tshirt
  description: '1 machine de 11kg, 2 machine de 7kg (équipe d''un distributeur de
    lessive) et 2 sèche linge '
  delay: 0.6s
- title: Local vélo
  delay: 0.8s
  description: fermé à clé (jusqu'a 15 vélos)
  icon: fa-biking
