services:
  - icon: fa-broom
    title: Ménage
    description: Description Ménage TODO
    delay: 0s

  - icon: fa-mug-hot
    title: Petit-déjeuner
    description: Description Petit-déjeuner TODO
    delay: 0.1s

  - icon: fa-spa
    title: Spa
    description: Sauna/Hammam
    delay: 0.2s

  - icon: fa-dumbbell
    title: Salle de sport
    description: Description Salle de sport TODO
    delay: 0.3s
