---
services:
- title: Ménage
  icon: fa-broom
  description: Description Ménage TODO
  delay: 0s
- title: Petit-déjeuner
  icon: fa-mug-hot
  description: Description Petit-déjeuner TODO
  delay: 0.5s
- title: Acceuil
  icon: fa-smile-beam
  description: Avec le sourrire
  delay: 0.4s
- title: Spa
  icon: fa-spa
  description: Sauna/Hammam
  delay: 0.2s
- title: Salle de sport
  icon: fa-dumbbell
  description: Description Salle de sport TODO
  delay: 0.3s
