---
services:
- title: 'Laverie '
  icon: ''
  description: '1 machine de 11kg, 2 machine de 7kg et 2 sèche linge '
  delay: 1s
- title: Ménage
  icon: fa-broom
  description: '1 fois tous les 15 jours compris dans les charges du loyer '
  delay: 1s
- title: Petit-déjeuner
  icon: fa-mug-hot
  description: En Salle ou en Chambre à vous de choisir (voir tarif)
  delay: 0.5s
- title: Acceuil
  icon: fa-smile-beam
  description: 7/7, 24/24, à votre service...
  delay: 0.4s
- title: Spa
  icon: fa-spa
  description: Sauna et Hammam privatisé
  delay: 0.9s
- title: Salle de sport
  icon: fa-dumbbell
  description: Ce maintenir en forme, c'est essentiel...
  delay: 0.3s
