---
label: Service
hide_body: true
fields:
- name: title
  type: text
  config:
    required: false
  label: Titre
- name: icon
  type: text
  config:
    required: false
  label: Icon
- name: description
  type: text
  config:
    required: false
  label: Description
- name: delay
  type: text
  config:
    required: false
  label: Delay
